---
title: apps\spy-strangles-with-put-hedge\main.Rmd
date: 2024-12-14
description: SPY 7dte 20delta strangles with put hedge analysis
---

```{r}
library(tidyverse)

box::use(
    packages / utils / aesthetics[nedhmn_palette, nedhmn_theme],
)
```

# Query results from big query 

```{r}
bq_tbl <- read_csv(
    file = "apps/spy-strangles-with-put-hedge/data/bq-strangles-data.csv",
    show_col_types = FALSE
)

# bq_tbl |>
#     head(15) |>
#     View()
```

# Calculate pnl

```{r}
pnls_tbl <- bq_tbl |>
    # select(contains("date"), expiration, contains("strangle"), tail_put_price_entry, tail_put_price_exit) |>
    mutate(
        strangle_dollar_pnl = strangle_price_exit - strangle_price_entry,
        short_strangle_dollar_pnl = strangle_dollar_pnl * -1,
        tail_put_dollar_pnl = tail_put_price_exit - tail_put_price_entry,
        position_dollar_pnl = short_strangle_dollar_pnl + tail_put_dollar_pnl
    )

# pnls_tbl
```

# EDA - Checking that the long put makes sense

```{r}
tail_put_tbl <- pnls_tbl |>
    mutate(tail_put_strike = as.numeric(substr(tail_put_id, nchar(tail_put_id) - 7, nchar(tail_put_id))) / 1000)

# When stock exit prices goes lower than put strike, all
# tail_put_dollar_pnl is $gt 0
tail_put_tbl |>
    filter(tail_put_strike > stock_price_exit) |>
    select(tail_put_dollar_pnl) |>
    summary()

#  tail_put_dollar_pnl
#  Min.   : 0.3300
#  1st Qu.: 0.7775
#  Median : 2.7250
#  Mean   : 5.9331
#  3rd Qu.:10.1762
#  Max.   :17.5400

# There's only been 8 instances since 2019 when the
# stock_price_exit passed the put strike
tail_put_tbl |>
    count(tail_put_strike > stock_price_exit)

# The tail put hedge has only made money 11 times.
tail_put_tbl |>
    count(tail_put_dollar_pnl > 0)

# The 3 times that tail put hedge pnl was positive
# that wasn't when the underlying was $lte to the put's strike
# is when it was very close to it. cont...
tail_put_tbl |>
    filter(tail_put_strike <= stock_price_exit &
        tail_put_dollar_pnl >= 0) |>
    View()

# ... for example, the mean percentage of the difference
# between the put's strike and the stock's exit price with the
# put's strike is ~0.0008.
tail_put_tbl |>
    filter(tail_put_strike <= stock_price_exit &
        tail_put_dollar_pnl >= 0) |>
    mutate(diff = stock_price_exit - tail_put_strike) |>
    select(tail_put_dollar_pnl, diff, tail_put_strike) |>
    mutate(pct_diff = diff / tail_put_strike) |>
    summary()

## --= Output ---
# tail_put_dollar_pnl      diff       tail_put_strike    pct_diff
#  Min.   :0.1200      Min.   :0.240   Min.   :385.0   Min.   :0.0006234
#  1st Qu.:0.3250      1st Qu.:0.330   1st Qu.:450.0   1st Qu.:0.0007195
#  Median :0.5300      Median :0.420   Median :515.0   Median :0.0008155
#  Mean   :0.4550      Mean   :0.390   Mean   :473.3   Mean   :0.0008066
#  3rd Qu.:0.6225      3rd Qu.:0.465   3rd Qu.:517.5   3rd Qu.:0.0008982
#  Max.   :0.7150      Max.   :0.510   Max.   :520.0   Max.   :0.0009808
```

# EDA - Short Strangles Delta

```{r}
# TODO
```

# EDA - Tail Put Delta

```{r}
put_delta_summaries <- pnls_tbl |>
    select(date_entry, tail_put_delta_entry) |>
    mutate(tail_put_delta_entry = abs(tail_put_delta_entry)) |>
    reframe(
        min_date = min(date_entry),
        max_date = max(date_entry),
        med_delta = median(tail_put_delta_entry),
        mean_delta = mean(tail_put_delta_entry),
        min_delta = min(tail_put_delta_entry),
        max_delta = max(tail_put_delta_entry),
        sd_delta = sd(tail_put_delta_entry),
        n = n()
    ) |>
    mutate(across(contains("delta"), function(x) round(x, 3)))

pnls_tbl |>
    select(date_entry, tail_put_delta_entry) |>
    ggplot(aes(abs(tail_put_delta_entry), fill = "name")) +
    geom_histogram(bins = 100) +
    scale_fill_manual(values = nedhmn_palette) +
    nedhmn_theme() +
    labs(
        title = "Absolute Tail Put Entry Deltas",
        subtitle = sprintf(
            "SPY 7dte put deltas from %s to %s (n=%s, µ=%s, min=%s, max=%s, sd=%s)",
            put_delta_summaries$min_date,
            put_delta_summaries$max_date,
            put_delta_summaries$n,
            put_delta_summaries$mean_delta,
            put_delta_summaries$min_delta,
            put_delta_summaries$max_delta,
            put_delta_summaries$sd_delta
        ),
        x = "Absolute Deltas",
        y = "Frequency"
    )

# ggsave("apps/spy-strangles-with-put-hedge/assets/tail-put-delta-distribution.png", height = 4, width = 8)
```

# EDA - Short Strangles PnL

```{r}
pnls_tbl |>
    ggplot(aes(short_strangle_dollar_pnl * 100, fill = "name")) +
    geom_histogram(bins = 100) +
    scale_fill_manual(
        values = nedhmn_palette
    ) +
    scale_x_continuous(labels = scales::dollar) +
    nedhmn_theme() +
    labs(
        title = "SPY Short Strangle Dollar PnL",
        # TODO - add descriptive statisitics here
        subtitle = sprintf(
            "20delta 7dte strangles from %s to %s",
            min(pnls_tbl$date_entry),
            max(pnls_tbl$date_entry)
        ),
        x = "Short Dollar PnL",
        y = "Frequency"
    )

# ggsave("apps/spy-strangles-with-put-hedge/assets/short-strangles-distribution.png", height = 4, width = 8)
```

# EDA - Long Tail Put PnL

```{r}
tail_put_summaries <- pnls_tbl |>
    select(date_entry, tail_put_dollar_pnl) |>
    mutate(tail_put_dollar_pnl = tail_put_dollar_pnl * 100) |>
    reframe(
        min_date = min(date_entry),
        max_date = max(date_entry),
        med = median(tail_put_dollar_pnl),
        mean = mean(tail_put_dollar_pnl),
        min = min(tail_put_dollar_pnl),
        max = max(tail_put_dollar_pnl),
        sd = round(sd(tail_put_dollar_pnl), 2),
        n = n()
    ) |>
    mutate(across(med:max, function(x) scales::dollar(x)))

pnls_tbl |>
    ggplot(aes(tail_put_dollar_pnl * 100, fill = "name")) +
    geom_histogram(bins = 100) +
    scale_fill_manual(
        values = nedhmn_palette
    ) +
    scale_x_continuous(labels = scales::dollar) +
    nedhmn_theme() +
    labs(
        title = "Long SPY Tail Put Dollar PnL",
        subtitle = sprintf(
            "7dte 2delta puts from %s to %s (n=%s, µ=%s, min=%s, max=%s, sd=%s)",
            tail_put_summaries$min_date,
            tail_put_summaries$max_date,
            tail_put_summaries$n,
            tail_put_summaries$mean,
            tail_put_summaries$min,
            tail_put_summaries$max,
            tail_put_summaries$sd
        ),
        x = "",
        y = "Frequency"
    )

# ggsave("apps/spy-strangles-with-put-hedge/assets/long-tail-put-pnl-distribution.png", height = 4, width = 8)
```

# EDA - Put Percent Of Short Strangles

```{r}
pct_of_strangle_summaries <- pnls_tbl |>
    select(date_entry, strangle_price_entry, tail_put_price_entry) |>
    mutate(put_pct_of_strangles = abs(tail_put_price_entry) / abs(strangle_price_entry)) |>
    reframe(
        min_date = min(date_entry),
        max_date = max(date_entry),
        med = median(put_pct_of_strangles),
        mean = mean(put_pct_of_strangles),
        min = min(put_pct_of_strangles),
        max = max(put_pct_of_strangles),
        sd = round(sd(put_pct_of_strangles), 2),
        n = n()
    ) |>
    mutate(across(med:max, function(x) scales::percent(x)))

pnls_tbl |>
    select(date_entry, strangle_price_entry, tail_put_price_entry) |>
    mutate(put_pct_of_strangles = abs(tail_put_price_entry) / abs(strangle_price_entry)) |>
    ggplot(aes(put_pct_of_strangles, fill = "name")) +
    geom_histogram(bins = 100) +
    scale_x_continuous(labels = scales::percent) +
    scale_fill_manual(values = nedhmn_palette) +
    nedhmn_theme() +
    labs(
        title = "Put Entry Price Percentage of Strangle Entry Price",
        subtitle = sprintf(
            "(n=%s, µ=%s, min=%s, max=%s, sd=%s)",
            pct_of_strangle_summaries$n,
            pct_of_strangle_summaries$mean,
            pct_of_strangle_summaries$min,
            pct_of_strangle_summaries$max,
            pct_of_strangle_summaries$sd
        ),
        x = "Put Entry Price Percentage of Strangle Entry Price",
        y = "Frequency",
        caption = str_wrap(
            "Put (7dte, 2delta) entry price percentage of strangle (7dte, 20delta) entry price"
        )
    )

# ggsave("apps/spy-strangles-with-put-hedge/assets/put-percentage-of-strangles-distribution.png", height = 4, width = 8)
```

# EDA - Summary statistics

```{r}
# TODO - Turn to gt table
pnls_tbl |>
    select(date_entry, short_strangle_dollar_pnl, position_dollar_pnl) |>
    pivot_longer(contains("pnl")) |>
    group_by(name) |>
    # mutate(value = value * 100) |>
    reframe(
        sum = sum(value),
        min = min(value),
        q1 = quantile(value, 0.25)[1],
        med = median(value),
        mean = mean(value),
        q3 = quantile(value, 0.75)[1],
        max = max(value),
        stddev = sd(value),
        n = n()
    )

# # TODO - Make clearer or discard
# pnls_tbl |>
#     select(date_entry, short_strangle_dollar_pnl, position_dollar_pnl) |>
#     pivot_longer(contains("pnl")) |>
#     ggplot(aes(x = value, fill = name, alpha = 0.2)) +
#     geom_density() +
#     scale_x_continuous(labels = scales::dollar) +
#     scale_fill_manual(values = nedhmn_palette[c(1, 3)]) +
#     nedhmn_theme()
```

# Calculate cumulative pnls

```{r}
cum_pnls_tbl <- pnls_tbl |>
    select(date_entry, short_strangle_dollar_pnl, position_dollar_pnl) |>
    arrange(date_entry) |>
    mutate(across(contains("pnl"), function(x) cumsum(x), .names = "cum_{.col}"))

cum_pnls_tbl |>
    pivot_longer(contains("cum")) |>
    ggplot(aes(x = date_entry, y = value * 100, color = name)) +
    geom_line() +
    scale_y_continuous(
        labels = scales::dollar
    ) +
    scale_color_manual(
        # values = viridis::viridis(3)[c(1, 2)],
        values = nedhmn_palette[c(1, 3)],
        labels = c(
            "cum_position_dollar_pnl" = "Hedged Short Strangle",
            "cum_short_strangle_dollar_pnl" = "Short Strangle"
        )
    ) +
    nedhmn_theme(show_legend = TRUE) +
    labs(
        title = "Short Strangle PnL With and Without Tail Put Hedge",
        subtitle = sprintf("SPY data from %s to %s", min(cum_pnls_tbl$date_entry), max(cum_pnls_tbl$date_entry)),
        x = "",
        y = "Cumulative PnL",
        color = "Legend",
        caption = str_wrap(
            "Short strangles are 20-delta, 7-dte, SPY strangles. Hedged short strangles adds a long 2-delta put. Each leg is 1 lot.",
            width = 100
        )
    )

# ggsave("apps/spy-strangles-with-put-hedge/assets/short-strangles-comparison-line-chart.png", height = 4, width = 8)
```

# Circled hedged short strangle pnl

```{r}
cum_pnls_tbl |>
    ggplot(aes(x = date_entry, y = cum_position_dollar_pnl * 100, color = "name")) +
    geom_line() +
    geom_point(
        data = cum_pnls_tbl[cum_pnls_tbl$position_dollar_pnl > cum_pnls_tbl$short_strangle_dollar_pnl, ],
        color = nedhmn_palette[4],
        size = 5,
        stroke = 1.5,
        shape = 1
    ) +
    scale_y_continuous(
        labels = scales::dollar
    ) +
    scale_color_manual(
        values = nedhmn_palette
    ) +
    nedhmn_theme() +
    labs(
        title = "Short Strangle with Circled Tail Put Hedge",
        subtitle = sprintf(
            "%s to %s",
            min(cum_pnls_tbl$date_entry),
            max(cum_pnls_tbl$date_entry)
        ),
        x = "",
        y = "Cumulative PnL",
        caption = str_wrap(
            "SPY 7dte 20delta short strangles with long 7dte 2delta put hedge. The circles are the times that the put made money.",
            width = 100
        )
    )

# ggsave("apps/spy-strangles-with-put-hedge/assets/circled-hedged-short-strangle-pnl.png", height = 4, width = 8)
```
