---
title: src\projects\contango-strategy\community-questions.Rmd
date: 2024-12-01
description: Answering follow-up questions for the contango strategy
---

# Libraries

```{r}
library(tidyverse)
setwd(paste0(getwd(), "/src/projects/contango-strategy"))
```

# Load data

```{r}
full_data <- read_csv(
    "data/full_data.csv",
    show_col_types = FALSE
)
```

# 1. Average strangle price

```{r}
# full_data |>
#     select(strangle_price_entry) |>
#     summary()

price_summaries <- full_data |>
    select(strangle_price_entry) |>
    pivot_longer(everything()) |>
    group_by(name) |>
    summarize(
        n = n(),
        mean = mean(value),
        sd = round(sd(value), 2),
        min = min(value),
        max = max(value)
    ) |>
    mutate(across(c(mean, min, max), function(x) scales::dollar(round(x, 2))))

full_data |>
    select(date_entry, strangle_price_entry) |>
    pivot_longer(strangle_price_entry) |>
    ggplot(aes(x = value, fill = name)) +
    geom_histogram(bins = 100) +
    scale_x_continuous(labels = scales::dollar) +
    scale_fill_manual(
        values = viridis::viridis(1, option = "E"),
        labels = c("strangle_price_entry" = "SPY")
    ) +
    labs(
        title = "SPY Strangle Prices",
        subtitle = sprintf(
            "Contango strategy's entry strangle prices (N=%s, M=%s, SD=%s, min=%s, max=%s)",
            price_summaries$n,
            price_summaries$mean,
            price_summaries$sd,
            price_summaries$min,
            price_summaries$max
        ),
        x = "Strangle Prices",
        y = "",
        fill = "Ticker"
    )

# ggsave("assets/strangle_price_distribution.png", height = 4, width = 8)
```

# 2. Average delta of strangle prices

```{r}
delta_tbl <- full_data |>
    mutate(strangle_delta = call_delta_entry + put_delta_entry) |>
    select(strangle_delta)

# delta_tbl |>
#     summary()

delta_summaries <- delta_tbl |>
    pivot_longer(everything()) |>
    group_by(name) |>
    summarize(
        n = n(),
        mean = round(mean(value), 4),
        sd = sd(value),
        min = min(value),
        max = max(value)
    ) |>
    mutate(across(sd:max, function(x) round(x, 2)))

delta_tbl |>
    pivot_longer(everything()) |>
    ggplot(aes(x = value, fill = name)) +
    geom_histogram(bins = 100) +
    scale_fill_manual(
        values = viridis::viridis(1, option = "E"),
        labels = c("strangle_delta" = "SPY Strangle")
    ) +
    labs(
        title = "SPY Strangle Deltas",
        subtitle = sprintf(
            "7DTE 20Delta Strangles (N=%s, M=%s, SD=%s, min=%s, max=%s)",
            delta_summaries$n,
            delta_summaries$mean,
            delta_summaries$sd,
            delta_summaries$min,
            delta_summaries$max
        ),
        x = "Delta",
        y = "",
        fill = ""
    )

# ggsave("assets/strangle_delta_distribution.png", height = 4, width = 8)
```

